exclude: _pb2\.py$
repos:
- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
    - id: black
- repo: https://github.com/asottile/yesqa
  rev: v1.1.0
  hooks:
  - id: yesqa
    additional_dependencies:
    - flake8-bugbear==20.1.4
    - flake8-builtins==1.5.2
    - flake8-comprehensions==3.2.2
    - flake8-tidy-imports==4.1.0
    - flake8==3.7.9
